# Generated by Django 4.1.7 on 2023-03-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_userchat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchat',
            name='user',
            field=models.CharField(max_length=40),
        ),
    ]
