# Generated by Django 4.1.7 on 2023-03-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usernamemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNameModel',
        ),
    ]
